sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ud2SZeOu64itn4uuhuqA1a/kKGmcPNNeSi5eOzKJxAffJ1tsqR62OPsjOlqySXZqmD2lm1wIxcm4NeduNpNBq9wiMZoCQzU0wmHu5DweYVI2w4yNZe/Eo3qk4IX6kyrP2/h499SObTUOHYfMT/HaFluqJHTTTie+ODtEy5qyWDXAv8Db9BZfbvs0wFHHcJ5Ur/sSafs+SB0Kmtj33TGIjUDhu5bBKzMbs5dZiht+rZCSCJegIjStfXA7PadofOeeC1gN/ifFtZ+l4lLnIQ44Mq/ud2Y/mYW49jTbGh787K/P0THdA3hzjmshvbYeBic00KPOQzVB6UMPbg3PytHZNrY2eg4/ZqjVfg9c3VxQjXSsolniaxWa0DBr5J1t9uMmNU4/J/y90IJzjwihhmIQDC3c/2BU1eVZ5mB9CrgEImKSP5XHPE7CNl0SCqHi5ZXtKuiqTLMSV0MCJo8Z8wReOKKvLJwG1GvBVzaDBvQY+IHD/2KKk3a1h030InYawLAhZfJoitikEhm2C6pDRMGqTN2ZFhmZYnd/7HLleeIv+K6evMB/Hxo7L1hpdWokX2GPpMLnMGVv4ZJq0t7lJHVHMUeHKm5Z47/36a9t0J4nW4bOsbedFckVD+qneCLgkPKBHxgi+RNNgGfltDV2IKXY5tO++9oqZX42q0x2xxex5U0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Real-Soldiers-of-Fortune_3029
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy